ShopProject/WebUI/Controllers/AdminController.cs
using Business.Abstract;
using Business.WebModels;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categoryService;
        public AdminController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }
        public IActionResult ProductLists()
        {
            return View(_productService.GetAll());
        }

        [HttpGet]
        public IActionResult CreateProduct()
        {
            return View(new ProductWM());
        }

        [HttpPost]
        public IActionResult CreateProduct(ProductWM model)
        {
            if (ModelState.IsValid)
            {
                var entity = new Product()
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    Image = model.Image
                };
                _productService.Create(entity);

                return RedirectToAction("ProductLists");
            }
            return View(model);
        }

        public IActionResult EditProduct(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = _productService.GetById((int)id);

            if (entity == null)
            {
                return NotFound();
            }

            var model = new ProductWM()
            {
                Id = entity.Id,
                Name = entity.Name,
                Price = entity.Price,
                Description = entity.Description,
                Image = entity.Image
                //SelectedCategories = entity.ProductCategories.Select(i => i.Category).ToList()

            };

            ViewBag.Categories = _categoryService.GetAll();

            return View(model);

        }

        [HttpPost]
        public IActionResult EditProduct(ProductWM model)
        {
            {
                var entity = _productService.GetById(model.Id);

                if (entity == null)
                {
                    return NotFound();
                }

                entity.Name = model.Name;
                entity.Description = model.Description;
                entity.Image = model.Image;
                entity.Price = model.Price;

                _productService.Update(entity);

                return RedirectToAction("ProductLists");
            }
        }

        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            var entity = _productService.GetById(productId);

            if (entity != null)
            {
                _productService.Delete(entity);
            }
            return RedirectToAction("ProductLists");
        }

        public IActionResult CategoryLists()
        {
            return View(_categoryService.GetAll());
        }
        [HttpGet]
        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCategory(CategoryWM model)
        {
            var entity = new Category()
            {
                Name = model.Name
            };
            _categoryService.Create(entity);

            return RedirectToAction("CategoryLists");
        }

        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            var entity = _categoryService.GetByIdWithProducts(id);

            return View(new CategoryWM()
            {
                Id = entity.Id,
                Name = entity.Name,
                Products = entity.ProductCategories.Select(p => p.Product).ToList()
            });
        }

        [HttpPost]
        public IActionResult EditCategory(CategoryWM model)
        {
            var entity = _categoryService.GetById(model.Id);
            if (entity == null)
            {
                return NotFound();
            }
            entity.Name = model.Name;

            _categoryService.Update(entity);

            return RedirectToAction("CategoryLists");

        }

        [HttpPost]
        public IActionResult DeleteCategory(int categoryId)
        {
            var entity = _categoryService.GetById(categoryId);

            if (entity != null)
            {
                _categoryService.Delete(entity);
            }
            return RedirectToAction("CategoryLists");
        }

        [HttpPost]
        public IActionResult DeleteFromCategory(int categoryId, int productId)
        {
            _categoryService.DeleteFromCategory(categoryId, productId);
            return Redirect("/admin/editcategory/" + categoryId);
        }
    }
}

ShopProject/WebUI/Controllers/CartController.cs
using Business.Abstract;
using Business.WebModels;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopApp.WebUI.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<ApplicationUser> _userManager;
        //private IOrderService _orderService;
        public CartController(ICartService cartService, UserManager<ApplicationUser> userManager)
        {
            //_orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            return View(new CartWM()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemWM()
                {
                    
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    Image = i.Product.Image,
                    Quantity = i.Quantity
                }).ToList()
            });
        }  
        [HttpPost]
        public IActionResult AddToCart(int productId,int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }



        public IActionResult Checkout()
        {

            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            var orderModel = new OrderWM();
            orderModel.CartWM = new CartWM()
            {

                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemWM()
                {
                    CartItemId=i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    Image = i.Product.Image,
                    Quantity = i.Quantity
                }).ToList()
            };
          
            return View(orderModel);
        }

        //    [HttpPost]
        //    public IActionResult Checkout(OrderWM model)
        //    {

        //        if (ModelState.IsValid)
        //        {
        //            var userId = _userManager.GetUserId(User);
        //            var cart = _cartService.GetCartByUserId(userId);

        //            model.CartWM = new CartWM()
        //            {
        //                CartId = cart.Id,
        //                CartItems=cart.CartItems.Select(i=>new CartItemWM()
        //                {
        //                    CartItemId=i.Id,
        //                    ProductId = i.Product.Id,
        //                    Name = i.Product.Name,
        //                    Price = (decimal)i.Product.Price,
        //                    Image = i.Product.Image,
        //                    Quantity = i.Quantity
        //                }).ToList()

        //            };
        //            SaveOrder(model, userId);
        //        }
        //        return RedirectToAction("Index");
        //    }


        //    private void SaveOrder(OrderWM model,string userId)
        //    {
        //        var order = new Order();


        //        order.OrderNumber = new Random().Next(111111, 999999).ToString();
        //        order.OrderDate = new DateTime();
        //        order.FirstName = model.FirstName;
        //        order.LastName = model.LastName;
        //        order.Email = model.Email;
        //        order.Phone = model.Phone;
        //        order.Address = model.Address;
        //        order.UserId = userId;

        //        foreach (var item in model.CartWM.CartItems)
        //        {
        //            var orderitem = new OrderItems()
        //            {
        //                Price = item.Price,
        //                Quantity = item.Quantity,
        //                ProductId = item.ProductId,
        //            };
        //            order.OrderItems.Add(orderitem);
        //        }
        //        _orderService.Create(order);

        //    }

    }
}

ShopProject/WebUI/Controllers/ShopController.cs
using Business.Abstract;
using Business.WebModels;
using Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categoryService;

        public ShopController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product product = _productService.GetProductDetails((int)id);

            if (product == null)
            {
                return NotFound();
            }
            return View(new ProductWM()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList()
            });
        }

        public IActionResult List(string category)
        {
            return View(_productService.GetProductsByCategory(category));
        }
    }
}

ShopProject/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>lighten</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="~/images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!--body-->

<body class="main-layout">
    <div class="loader_bg">
        <div class="loader"><img src="~/images/loading.gif" alt="#" /></div>
    </div>

    <partial name="_navbar" />

    <div>
        @RenderBody()
    </div>


    <!--ara-->
    <div class="container">
        <div class="yellow_bg">
            <div class="row">
                <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12">
                    <div class="yellow-box">
                        <h3>BİZLERE ULAŞIN<i><img src="~/icon/calll.png" /></i></h3>

                        <p>Artık her şey çok kolay bir tıkla kapında</p>
                    </div>
                </div>
                <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
                    <div class="yellow-box">
                        <a href="#">Sipariş Ver</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--ara son-->

    <!--footer-->
    <footr>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <ul class="sociel">
                            <li> <a href="#"><i class="fa fa-facebook-f"></i></a></li>
                            <li> <a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li> <a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>Bize Ulaşın</h3>
                            <span>
                                123 İkiler Sokak Beşinci Cadde,<br>
                                Manhattan, New York<br>
                                +987 654 3210
                            </span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>Ek Bağlantılar</h3>
                            <ul class="lik">
                                <li> <a href="#">Hakkımızda</a></li>
                                <li> <a href="#">Şartlar ve Koşullar</a></li>
                                <li> <a href="#">Gizlilik Politikası</a></li>
                                <li> <a href="#">Bize Ulaşın</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>Hizmetler</h3>
                            <ul class="lik">
                                <li> <a href="#">Ücretsiz İade</a></li>
                                <li> <a href="#">Ücretsiz Değişim</a></li>
                                <li> <a href="#">Kargo Bedava</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>Site Hakkında</h3>
                            <span>
                                Müşterilerimize ve tedarikçilerimize kusursuz bir e-ticaret deneyimi yaşatmak için 2010’da kurulduk.
                                Bugün Türkiye'nin en büyük e-ticaret şirketi, dünyanın ise önde gelen platformlarından biriyiz.
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <p>Copyright 2019 All Right Reserved By <a href="https://html.design/">Free html Templates</a></p>
            </div>
        </div>
    </footr>
    <!--footer son-->

    <!-- Javascript files-->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-3.0.0.min.js"></script>
    <script src="~/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function () {

                $(this).addClass('transition');
            }, function () {

                $(this).removeClass('transition');
            });
        });

    </script>

</body>
</html>

ShopProject/WebUI/Views/Shared/_navbar.cshtml
<div class="header">
    <div class="head_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="top-box">
                        <ul class="sociel_link">
                            <li> <a href="#"><i class="fa fa-facebook-f"></i></a></li>
                            <li> <a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li> <a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li> <a href="#"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="top-box">
                        <p>Online Alışverişin Adresi </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-2 col logo_section">
                <div class="full">
                    <div class="center-desk">
                        <div class="logo"><a asp-controller="Home" asp-action="Index"><img src="~/images/logo.jpg" alt="logo" /></a> </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="col-sm-12">
                    <div class="menu-area">
                        <div class="limit-box">
                            <nav class="main-menu">

                                <ul class="menu-area-main">
                                    <li class="nav-item">
                                        <a asp-controller="Shop" asp-action="List">Ürünler</a>
                                    </li>
                                </ul>

                            </nav>
                                @if (User.Identity.IsAuthenticated)
                                {
                        <nav class="main-menu">
                            <div class="dib">
                                <ul class="menu-area-main">
                                    <li class="nav-item">
                                        <a asp-controller="Cart" asp-action="Index">Sepet</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="dib">
                                <ul class="menu-area-main">
                                    <li class="nav-item">
                                        <a asp-controller="Cart" asp-action="Order">Siparişler</a>
                                    </li>
                                </ul>
                            </div>
                                </nav>
                                }
                                @if (User.IsInRole("admin"))
                            {
                                <nav class="main-menu">
                                    <div class="dib">
                                        <ul>
                                            <li class="nav-item">
                                                <a asp-controller="Admin" asp-action="CreateProduct">Ürün Ekle</a>
                                            </li>
                                        </ul>
                                    </div>
                                </nav>

                                 <nav class="main-menu">
                                     <div class="dib">
                                         <ul>
                                             <li class="nav-item">
                                                 <a asp-controller="Admin" asp-action="ProductLists">Admin Ürün</a>
                                             </li>
                                         </ul>
                                     </div>
                                 </nav>

                                 <nav class="main-menu">
                                     <div class="dib">
                                         <ul>
                                             <li class="nav-item">
                                                 <a asp-controller="Admin" asp-action="CreateCategory">Kategori Ekle</a>
                                             </li>
                                         </ul>
                                     </div>
                                 </nav>

                                 <nav class="main-menu">
                                     <div class="dib">
                                         <ul>
                                             <li class="nav-item">
                                                 <a asp-controller="Admin" asp-action="CategoryLists"> Admin Kategori</a>
                                             </li>
                                         </ul>
                                     </div>
                                 </nav>
                            
                            }
                        
                    @if (User.Identity.IsAuthenticated)
                    {
                            <ul>
                                <li><a class="buy-account" asp-controller="Account" asp-action="Logout">Çıkış Yap</a></li>
                            </ul>

                            <ul>
                                <li><a class="buy-account" asp-controller="Account" asp-action="Manage"> @User.Identity.Name</a></li>
                            </ul>
                     }

                    else

                    {
                       
                            <ul>
                                <li>
                                    <a class="buy-account" asp-controller="Account" asp-action="Login">Oturum Aç</a>
                                </li>
                            </ul>
                            
                            <ul>
                                <li>
                                    <a class="buy-account" asp-controller="Account" asp-action="Register">Kayıt Ol</a>
                                </li>
                            </ul>
                       
                    }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ShopProject/WebUI/Views/Shared/_product.cshtml
@model Product

<div class="col-md-4">
    <div class="card mb-3">
        <img src="~/images/@Model.Image" alt="@Model.Name" />
        <div class="card-body">
            <h4 class="card-title">
                <a href="#">@Model.Name</a>
            </h4>
            <small class="text-muted">
                <i class="fas fa-lira-sign"></i>@Model.Price
            </small>
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="send">Detaylar</a>
            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline;">
                    <input type="hidden" name="productId" value="@Model.Id" />
                    <input type="hidden" name="quantity" value="1" />
                        <button type="submit" class="send" style="display:inline;">Sepete Ekle</button>
                </form>
            }

        </div>
    </div>
</div>

ShopProject/WebUI/Views/Shared/_slider.cshtml
<div class="container">
        <section class="slider_section">
            <div id="main_slider" class="carousel slide banner-main mb-3" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <center><img class="first-slide" src="~/images/slider1/slider1.jpg" alt="First slide"></center>
                        <div class="container">
                            <div class="carousel-caption relative">
                                <h1>
                                    Son <br> <strong class="black_bold">Kalan </strong><br>
                                    <strong class="yellow_bold">Ürünler </strong>
                                </h1>
                                <p>
                                    En uygun fiyatlarla <br>
                                    bütün kıyafetler burada
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <center><img class="second-slide" src="~/images/slider2.jpg" alt="Second slide"></center>
                        <div class="container">
                            <div class="carousel-caption relative">
                                <h1>
                                    Birbirinden <br> <strong class="black_bold">Renkli </strong><br>
                                    <strong class="yellow_bold">Parçalar </strong>
                                </h1>
                                <p>
                                    Kaliteli ve renkli kumaşlar... <br>
                                    Çok seveceksiniz
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <center><img class="third-slide" src="~/images/slider3.jpg" alt="Third slide"></center>
                        <div class="container">
                            <div class="carousel-caption relative">
                                <h1>
                                    Tarzınızı <br> <strong class="white_bold">Her yere </strong><br>
                                    <strong class="yellow_bold">Yansıtın </strong>
                                </h1>
                                <p>
                                    İçiniz dışınıza yansısın... <br>
                                    Siyah ve beyazın eşsiz uyumu...
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
                    <i class='fa fa-angle-right'></i>
                </a>
                <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
                    <i class='fa fa-angle-left'></i>
                </a>
            </div>

        </section>
   </div>